function [A,B,C,D] = gen_twolink_ss(L_1x,L_1y,L_2x,L_2y,b1,b2,m1,m2)
%GEN_TWOLINK_SS
%    [A,B,C,D] = GEN_TWOLINK_SS(L_1X,L_1Y,L_2X,L_2Y,B1,B2,M1,M2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    15-Jun-2022 09:58:31

A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,(b1.*-1.2e+1)./(L_1x.^2.*m1.*4.0+L_1x.^2.*m2.*1.2e+1+L_1y.^2.*m1+L_2x.^2.*m2.*3.0),0.0,0.0,1.0,0.0,(b2.*-1.2e+1)./(m2.*(L_2x.^2.*4.0+L_2y.^2))],[4,4]);
if nargout > 1
    B = reshape([0.0,0.0,1.2e+1./(L_1x.^2.*m1.*4.0+L_1x.^2.*m2.*1.2e+1+L_1y.^2.*m1+L_2x.^2.*m2.*3.0),0.0,0.0,0.0,0.0,1.2e+1./(m2.*(L_2x.^2.*4.0+L_2y.^2))],[4,2]);
end
if nargout > 2
    C = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0],[4,4]);
end
if nargout > 3
    D = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,2]);
end
